Python script to send SMS
amitsagtani97/Python-Scripts pull request #6
Opened 2017-10-14 10:39 UTC by soumya-ranjan7

A simple python script to send SMS.

2017-10-14 12:57 UTC, amitsagtani97 requested changes
can you please create a new directory and move this file into that directory with a README file :)

2017-10-14 13:28 UTC, soumya-ranjan7 commented
Requested changes have been made.

2017-10-16 08:38 UTC, amitsagtani97 commented on Sending_SMS/README.md
> +This a simple python script to send SMS to any desired phone number through Sinch messaging service (free of cost).
@soumya-ranjan7 Can you please add a link to Sinch API, where user can sign up and get a API Key to use your script.

2017-10-16 09:25 UTC, soumya-ranjan7 commented
Link to Sinch SMS API has been added.

2017-10-16 09:29 UTC, amitsagtani97 commented
@soumya-ranjan7  thanks for the PR. :) :+1:

2017-10-16 09:29 UTC, merged